### ISSUE TITLE
Convert Checkboxes to Toggle Switch

### ISSUE THREAD

**Issue by jared-leddy** [WPFedora/WordPress-Fedora#2]
These would look ALOT better as a toggle switch instead of a checkbox. 

![image](https://github.com/user-attachments/assets/850ea92a-5b24-4b68-9e8e-316074541a47)

**Comment by GoogleSEOMastermind** [comment]
We're using checkboxes instead of toggles to keep things simple and reduce unnecessary code. Checkboxes are natively supported in WordPress, so they work out-of-the-box with core functions like get_option and update_option without needing any extra code

If we switched to toggles, we’d have to add additional CSS and JavaScript to create the toggle effect, which adds complexity and potential issues for people depending on what themes/plugins/page-builders are being used. This is one of the reasons Zynith SEO wont always render and display settings correctly, primarily due to working outside of WordPress's native functions and option selection

**Comment by jared-leddy** [comment]
I definitely understand the premise of wanting to stay native with everything. In my head, the current ACF UI is a gold standard. Seems like a good place to want to be. 

In terms of the CSS/JS being added, it's really not that much. Here is a CSS only example of still [using a checkbox input, but showing users a toggle](https://codepen.io/singhimalaya/pen/EdVzNL). 

The idea being, if our logic doesn't change, we should be able to beautify it how we want to.

**Comment by jared-leddy** [comment]
Rejected by user preference.
